# Single-platform variant of browserstack.yml.
# `bundle exec rake single` copies this file to ./browserstack.yml before running.
userName: YOUR_USERNAME
accessKey: YOUR_ACCESS_KEY

projectName: BrowserStack Samples
buildName: cucumber-ruby-sdk-build-1
buildIdentifier: '#${BUILD_NUMBER}'

framework: cucumber

platforms:
  - os: Windows
    osVersion: 11
    browserName: chrome
    browserVersion: latest

parallelsPerPlatform: 1
browserstackLocal: false

debug: true
networkLogs: false
consoleLogs: errors

source: cucumber-ruby-sdk:sample-master:v1.0
