server: hub.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  build: browserstack-build-1
  browserstack.debug: true
  name: BStack local cucumber-ruby
  browserstack.source: cucumber-ruby:sample-master:v1.1
  

browser_caps:
- browser: chrome
  browserstack.local: true
