server: hub.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESS_KEY

common_caps:
  build: browserstack-build-1
  browserstack.debug: true
  name: BStack parallel cucumber-ruby
  browserstack.source: cucumber-ruby:sample-master:v1.1

browser_caps:
- browser: chrome
- browser: firefox
- browser: edge
- browser: safari
